spring:
  datasource:
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/clients

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
